### PR TITLE
Improve upsell section design

### PR DESCRIPTION
**Pull request by girishpanchal30**
Close Codeinwp/visualizer-pro#314

### CODE REVIEW

**Comment by girishpanchal30** [comment]
@selul Please review upsell section design and do let me know if you have any queries.

Thanks

**Comment by selul** [comment]
@girishpanchal30 will leave this for @irinelenache to do, please move it to testing.

**Comment by irinelenache** [comment]
@girishpanchal30 Tested and found a few things:

- [ ] The **check icons** are not vertically aligned with the features text https://vertis.d.pr/Ucsyhb
- [ ] The upsell card doesn't have the same height as the other cards in the chart library https://vertis.d.pr/JoIIiP
- [ ] When i change wordpress color scheme, the **Get visualizer pro** text on the dashboard tab has a hover color https://vertis.d.pr/XNCMUL (with the default color scheme, doesn't have any hover color) 
- [ ] When only one chart/no chart is created, the upsell card has the size of 2 charts https://vertis.d.pr/vUW3BG . Did we agree to use both approaches from @mghenciu ?

**Comment by girishpanchal30** [comment]
@irinelenache Fixed 3 points, Please retest again

**Comment by mghenciu** [comment]
As Irinel mentioned, @girishpanchal30, we agreed to use only the 1-column upsell message:
image

2 other things I noticed after doing a quick test with the build:

- [ ] when opening the **Get Visualizer Pro** button/menu, the link should open in New Tab. That's more of a general rule for upsell messages, to open them in a New Tab - instead of the current one (because this can be annoying for users).
Screenshot 2022-03-02 at 13 52 51

- [ ] **View more features button** in the upsell, should take users to [this Section](https://themeisle.com/plugins/visualizer-charts-and-graphs/upgrade/#features). I know previously it was leading to the Pricing section, but now things are different because we have the **Get Visualizer Pro** button in the Sidebar.

- [ ] I noticed now that the Upsell box looks good on a <1366px width, but on bigger screens the Upsell Box looks way too empty (second image)
image
 
Screenshot 2022-03-02 at 14 17 40

So to not waste the work you've already done with 2 columns, I would add the logic so if the Window width is bigger than 1366px, then show all 12 Visualizer Pro benefits, but **in one column**, and also only if width is >1366px make the column `height: fit-content;`. So it would look something like this:
image

On smaller screens <1366px, we'll keep only 6 checkmarks/benefits visible, and the Column `height: 100%`

___

As always, let me know if I can help with something else.
and sorry for asking last-mile changes, I'll try to avoid them in future.

**Comment by girishpanchal30** [comment]
> As always, let me know if I can help with something else.

@mghenciu Sure thank you

**Comment by girishpanchal30** [comment]
Hello @mghenciu, I have applied your mentioned suggestion, Please check and do let me know if you have any queries.

cc @irinelenache
Thanks

**Comment by irinelenache** [comment]
@girishpanchal30 Tested again and the mentioned issues are fixed, thank you 👍 

A single problem:

- [ ] This is how the upsell looks on my end:

image

Tested with Safari/Chrome on Macbook pro - Built-in Retina Display 13,3-inch (2560 × 1600)

**Comment by girishpanchal30** [comment]
@irinelenache  @mghenciu I'm looking into this issue, I'll update you here...

**Comment by girishpanchal30** [comment]
@irinelenache @mghenciu I have fixed mentioned issue, Please retest and let me know if you have any issues.
Thanks

**Comment by mghenciu** [comment]
I think it looks good @girishpanchal30, from my side.
Laptop (6 checkmarks):
image

Large screen (12 checkmarks):
image

**Comment by irinelenache** [comment]
@girishpanchal30 Tested again and everything looks fine for me too, thank you 👍

**Pull request merged**
