### PR TITLE
feat: show chart type select within frame

### PR DESCRIPTION
**Pull request by preda-bogdan**
### Summary

Added chart select inside the first step iframe.
Chart selection is visible in Free.
Changed styles.

### Will affect the visual aspect of the product

YES

### Screenshots 
<details open>
    <summary>Select within iFrame</summary>

image
</details>

### Test instructions

1. On a fresh instance with Visualizer installed
2. Check that when adding a new Chart the select for the chart engine is visible within the iframe
3. Check that it is working as before when Pro is activated

## Check before Pull Request is ready:

* [x] I have [written a test](CONTRIBUTING.md#writing-an-acceptance-test) and included it in this PR
* [x] I have [run all tests](CONTRIBUTING.md#run-tests) and they pass
* [x] The code passes when [running the PHP CodeSniffer](CONTRIBUTING.md#run-php-codesniffer)
* [x] Code meets [WordPress Coding Standards](CONTRIBUTING.md#coding-standards) for PHP, HTML, CSS and JS
* [x] [Security and Sanitization](CONTRIBUTING.md#security-and-sanitization) requirements have been followed
* [x] I have assigned a reviewer or two to review this PR (if you're not sure who to assign, we can do this step for you)

Closes Codeinwp/visualizer-pro#447.

### CODE REVIEW

**Review by Soare-Robert-Daniel — APPROVED** [review]

**Comment by irinelenache** [comment]
@preda-bogdan Tested and here is what i found:

- [ ] Everytime i select a different chart and open the library select, the word "PREMIUM" will duplicate https://vertis.d.pr/v/ICKgRt
- [ ] Libraries that are not available will still be visible in the select (for example, DataTable is visible for every chart) https://vertis.d.pr/i/rl0EUC

Can be checked here:
```
 Admin area URL: https://haplessview.s3-tastewp.com/wp-admin 
 Username: irinel 
 Password: LvSKOqU2RjU 
```

**Comment by Soare-Robert-Daniel** [comment]
> * [ ]  Libraries that are not available will still be visible in the select (for example, DataTable is visible for every chart) https://vertis.d.pr/i/rl0EUC

This will be a part of https://github.com/Codeinwp/visualizer-pro/issues/456

**Comment by preda-bogdan** [comment]
@irinelenache Thank you for looking into this. The duplicate labels issue should be solved now.
For the second one, @Soare-Robert-Daniel is right, this is a known bug that we will address separately.

Let me know if you find anything else. Thank you!

**Comment by irinelenache** [comment]
@preda-bogdan The mentioned issue is fixed now, thank you 🚀

**Comment by Soare-Robert-Daniel** [comment]
@preda-bogdan I fixed the compatibility with my changes of that selector.

One thing remains: the premium labels are kind of obsoleted since Line & Pie of ChartJS are not available for Free and we no longer have a dedicated lib for Premium users

**Comment by preda-bogdan** [comment]
@Soare-Robert-Daniel I checked the new behavior, fixed the conflicts, and updated the test to match the new requirements.

**Pull request merged**
