### PR TITLE
Database import - with queries from db

### PR DESCRIPTION
**Pull request by selul**

### CODE REVIEW

**Comment by rodica-andronache** [comment]
@contactashish13 please resolve the conflicts here

**Comment by contactashish13** [comment]
@rodica-andronache done

**Comment by SilviuDinu** [comment]
I've been testing this with Ash's help and coming from someone with little to none experience with SQL queries I would suggest adding some sort of short description to every option. Like a short "this will import the columns" "this will group the results for the given criteria". We can actually make a doc to make more intuitive.

when trying to create a chart with 2 columns (one of them is of type string) there is an error saying that the first column should be type string even though it is. It is not prioritizing the given column order, it's always taking the "count" column as the first one and it's not working because it is not of type string.
This behaviour for the pie chart can be observed here -> https://share.vidyard.com/watch/wrhCDUAAnzr3UFSDPc9DKt.
A similar behaviour can be observed for other charts as well.

**Comment by ineagu** [comment]
I guess we can make things much easier once we have table chart in free and launch this as well

**Pull request closed without merging**
