### PR TITLE
fix: switch to 10 minutes cron

### PR DESCRIPTION
**Pull request by Soare-Robert-Daniel**
### Summary

- Use 10 minutes cron instead of hourly
- Small refactor on the schedules update

### Will affect visual aspect of the product

NO

### Screenshots 

image

### Test instructions

- Check the Cron and see if its 10 minutes

## Check before Pull Request is ready:

* [x] I have [written a test](CONTRIBUTING.md#writing-an-acceptance-test) and included it in this PR
* [x] I have [run all tests](CONTRIBUTING.md#run-tests) and they pass
* [x] The code passes when [running the PHP CodeSniffer](CONTRIBUTING.md#run-php-codesniffer)
* [x] Code meets [WordPress Coding Standards](CONTRIBUTING.md#coding-standards) for PHP, HTML, CSS and JS
* [x] [Security and Sanitization](CONTRIBUTING.md#security-and-sanitization) requirements have been followed
* [x] I have assigned a reviewer or two to review this PR (if you're not sure who to assign, we can do this step for you)

Closes https://github.com/Codeinwp/visualizer-pro/issues/474

### CODE REVIEW

**Review by preda-bogdan — APPROVED** [review]

**Comment by rodica-andronache** [comment]
@Soare-Robert-Daniel tested and it's working well 👍

**Comment by vytisbulkevicius** [comment]
@Soare-Robert-Daniel,

I tested this with the final merge and it doesn't work to me. Charts are getting refreshed only after one hour not each ten minutes.

I see that the code change added here: https://github.com/Codeinwp/visualizer/pull/1161/files#diff-6a2bceb3434041451d4f3359e058407647985c3f74f400623aeafe9675cd0b92R213

Change the Recurrence of visualizer_schedule_refresh_db to 10 minutes, however, there is also visualizer_schedule_import hook that remains 1 hour and because of it the chart doesn't get refresh.

I changed the code in my test instance to:

> wp_clear_scheduled_hook( 'visualizer_schedule_refresh_db' );
> wp_clear_scheduled_hook( 'visualizer_schedule_import' );
> wp_schedule_event( strtotime( 'midnight' ) - get_option( 'gmt_offset' ) * HOUR_IN_SECONDS, apply_filters( 'visualizer_chart_schedule_interval', 'visualizer_ten_minutes' ), 'visualizer_schedule_refresh_db' );
> wp_schedule_event( strtotime( 'midnight' ) - get_option( 'gmt_offset' ) * HOUR_IN_SECONDS, apply_filters( 'visualizer_chart_schedule_interval', 'visualizer_ten_minutes' ), 'visualizer_schedule_import' );

So added same for visualizer_schedule_import as you did for visualizer_schedule_refresh_db and then it worked - charts got refreshed after 10 minutes.

Can you fix this?

Thanks!

**Comment by Soare-Robert-Daniel** [comment]
As an idea, `'visualizer_schedule_refresh_db' ` indirectly call `'visualizer_schedule_import'`.

The route is like this:
- At every 10 minutes, `'visualizer_schedule_refresh_db' ` is called.
- This updates the schedule times for the charts; if one of the charts needs to be updated, this triggers this function https://github.com/Codeinwp/visualizer/blob/4184b7eb205c50fee5758b7763d8deda3a51fb26/classes/Visualizer/Module/Setup.php#L427 
- And in case of remote CSV, it invokes the same hooks as the schedule for `'visualizer_schedule_import'`https://github.com/Codeinwp/visualizer/blob/4184b7eb205c50fee5758b7763d8deda3a51fb26/classes/Visualizer/Module/Setup.php#L349

Technically, the second schedule is not needed **unless** the first schedule is missing a chart type to update that the second might not. 

**What type of source (along with the URL) did you use?**

**Comment by vytisbulkevicius** [comment]
Hi @Soare-Robert-Daniel,

Any update here?

**Comment by Soare-Robert-Daniel** [comment]
@vytisbulkevicius, here is the PR https://github.com/Codeinwp/visualizer-pro/pull/481

I also created this issue https://github.com/Codeinwp/visualizer-pro/issues/482

Sorry for the issue. My attention and understanding are not in the best shape 😞, I misinterpreted the process.

**Pull request merged**
