### PR TITLE
3.3.0

### PR DESCRIPTION
**Pull request by contactashish13**

### CODE REVIEW

**Comment by contactashish13** [comment]
@DanyCaissy have updated this with a few changes for datatables and an instance of the json import not working.

**Comment by contactashish13** [comment]
@DanyCaissy you should now be able to add already created datatables using the block editor.

**Comment by contactashish13** [comment]
@DanyCaissy have added a few more changes:
- UI in the library (alignment of the search bar, a new `add new` button)
- consistent and descriptive error messages
- the `All` tab

**Comment by DanyCaissy** [comment]
Great, I'll take a look.

**Comment by contactashish13** [comment]
@DanyCaissy I have fixed the issues with datatables. Please refresh this branch and clear your browser cache before testing.

**Comment by DanyCaissy** [comment]
@contactashish13  Updated today and the error seems fixed

**Comment by contactashish13** [comment]
@DanyCaissy the latest chnage should fix the issue with gauge and candlesticks being shown as unavailable despite pro being active.

**Comment by DanyCaissy** [comment]
@contactashish13 Nice, I'll check these Monday

**Comment by DanyCaissy** [comment]
That seems to be fixed.

**Comment by contactashish13** [comment]
@DanyCaissy if you update your branch for both free (3.3.0) and pro (the branch is called 1.8.4 and I can't seem to rename it but the release will be v1.9.0), all combinations of free and pro should work correctly except for the problems on your instance with:

- new free, old pro
- old free, new pro

Your problems stem from the fact that we assume the Pro to be loaded and in your instance, somehow Pro appears to be loaded sometimes and not the other times. That is why #466 was needed to fix this problem for good. Please test and let me know what you find.

**Comment by DanyCaissy** [comment]
Okay, I'll update the 3.3 and install the new pro version and test these later.

**Comment by contactashish13** [comment]
@DanyCaissy @SilviuDinu https://github.com/Codeinwp/visualizer/issues/486#issuecomment-519082657 fixes a few UX/UI issues. Can you please test?

**Pull request merged**
