### PR TITLE
omit left in legend position for bubble chart

### PR DESCRIPTION
**Pull request by contactashish13**
#771

### CODE REVIEW

**Comment by irinelenache** [comment]
@contactashish13 when i try to create a new chart i get this error in log [debug.txt](https://github.com/Codeinwp/visualizer/files/5487422/debug.txt) and this in the console https://prnt.sc/vd89k0

**Comment by rodica-andronache** [comment]
@irinelenache the error seems to be coming from Neve, when used with Visualizer. And it's not related just to this PR. I've created an issue for it here https://github.com/Codeinwp/neve/issues/2254

**Comment by rodica-andronache** [comment]
@contactashish13 can you please fix the conflicts so we can merge it?

**Comment by contactashish13** [comment]
@rodica-andronache done

**Pull request merged**
