### PR TITLE
Added Gutenberg Block

### PR DESCRIPTION
**Pull request by HardeepAsrani**
Added Gutenberg Block which allows users to preview, edit and render existing charts, with the ability to create new charts in an upcoming release. It addresses: #282

### CODE REVIEW

**Comment by HardeepAsrani** [comment]
@selul @contactashish13 Would appreciate y'll to review this extensively. 😄

**Comment by contactashish13** [comment]
@HardeepAsrani 

- the upload button is still disabled and does not get enabled when a file is selected. I've cleared my browser cache as well.
- if I remove the disabled attribute using inspector and click upload, nothing happens. 
- I get this console error as soon as I load an empty post

image

- I'm not sure why the build JS files are created under classes/Visualizer/Gutenberg... shouldn't they be created somewhere outside rather than inside the source?
- I had a combo chart that I inserted. Using the manual editor I highlighted the last column, deleted it and clicked save. It gave me a console error. If I click the save button under the chart, it gives me the same console error again.
- scheduled charts cannot work because the `options` table is not being populated

image

**Comment by HardeepAsrani** [comment]
@contactashish13 Thanks, will see these and fix. For the disable issue, can @UVLabs also help in testing, given he uses a Windows with Chrome?

And can you also try to disable all browser extensions and try @contactashish13 because Gutenberg is weird and I've faced issues in past because of Redux Development Tools browser extension.

**Comment by HardeepAsrani** [comment]
`I get this console error as soon as I load an empty post`

Do you have that old Visualizer Gutenberg Integration plugin installed? This error is probably because the block already exists and we're loading it twice.

**Comment by HardeepAsrani** [comment]
Okay, so I guess you are still using the Visualizer Gutenberg Integration plugin and your review was of that block, because in Visualizer the button isn't disabled in the first place. 😄 

Delete `visualizer-gutenberg-integration` plugin and then try again. :)

**Pull request merged**
