### PR TITLE
Render chart image for AMP theme

### LINKED ISSUE #786: Mobile display of charts
Not sure this is the right place to mention this, but the way Visualizer handles charts on mobile is not very good.

Check out this post https://www.codeinwp.com/blog/how-to-invest-in-stocks/

The charts on mobile get converted to raw data tables. chart bad

This is not useful to the reader at all.

It could simply look like this chart good

And if not this, then the chart can be converted to an image file. I think we had something like that before.

cc @selul

### PR DESCRIPTION
**Pull request by girishkrishaweb**
Close #786

### CODE REVIEW

**Comment by irinelenache** [comment]
@girishkrishaweb I tried to test it with AMP and this patch doesn't fix the problem, you can check here:
```
https://holy-albatross.jurassic.ninja/2021/06/07/visualizer-amp/
user: demo
pass: bRvuNjGE39DZ
```
Let me know if i didn't test it correctly

**Comment by girishkrishaweb** [comment]
@irinelenache Yeah, this happened due to the existing chart, You have to re-save the chart to generate a new image or create a new chart to test it.

**Comment by irinelenache** [comment]
@girishkrishaweb Thanks for the info!
The charts work fine (https://prnt.sc/14jcw4s), but when i click the image to see it, it looks cropped (https://prnt.sc/14jcyzd)

**Comment by girishkrishaweb** [comment]
@irinelenache Solved the issue when you click on the image for the AMP theme.

**Comment by irinelenache** [comment]
@girishkrishaweb 
- [ ] Can the chart images be made bigger? They look small in the page and i have to zoom the page to actually read the values https://prnt.sc/14otueb
- [ ] The fix doesn't work for these charts: Radar/Spider, Timeline, Gauge

**Comment by girishkrishaweb** [comment]
**Can the chart images be made bigger? They look small in the page and i have to zoom the page to actually read the values https://prnt.sc/14otueb**
Sorry, it is not possible as we are using the full-size/high-resolution image right now.

**Comment by girishkrishaweb** [comment]
@selul We are not using any custom height/width for the chart image. we just print `wp_get_attachment_image()` to render image and it is converting to amp-img tag. 
chart-image-height-width

**Comment by selul** [comment]
@girishkrishaweb can we have a shortcode attribute that will render the image, indiferently of the device used. something like use_image='yes'

**Comment by selul** [comment]
also, when the image mode is used, we should not load any style/scripts that was needed on the JS mode.

**Comment by irinelenache** [comment]
@girishkrishaweb The shortcode attribute works fine, except for **Timeline** and **Gauge** . These charts' images don't work neither in AMP or with shortcode

**Comment by girishkrishaweb** [comment]
@irinelenache We have tested both the charts and both are not supported to generate a chart image. We are doing R&D on it and will update you soon!
chart-image-not-support

Also, The download functionality is not working on it due to the above reason.

**Comment by girishkrishaweb** [comment]
@irinelenache Can you please check **Timeline** and **Gauge** chart with the above patch?

**Comment by irinelenache** [comment]
@girishkrishaweb tested and they still don't work

**Comment by girishkrishaweb** [comment]
@irinelenache Please test with **AMP** and **Shortcode Attributes**. Thanks

**Comment by irinelenache** [comment]
@girishkrishaweb tested again and all charts work fine now 👍 
if @selul approves with the chart dimensions, this can be merged

**Pull request merged**
