### PR TITLE
SEO changes

### PR DESCRIPTION
**Pull request by DanyCaissy**

### CODE REVIEW

**Comment by DanyCaissy** [comment]
@contactashish13 Hi Ash, could you review these and let me know when it is merged?

Thanks

**Comment by contactashish13** [comment]
@DanyCaissy since you are changing the name of the plugin, can you also change it in the index.php?

@selul can you see if the name change will affect the license?

**Comment by selul** [comment]
@DanyCaissy to complete @contactashish13 feedback, changing the name in the readme.txt file will change the name on wordpress.org, changing the name on index.php will change the name in the WordPress admin, plugin listing area. 

@contactashish13 there is no license for the free version, so this is not affected.

**Comment by DanyCaissy** [comment]
@contactashish13  I've renamed it in index.php as well

**Comment by contactashish13** [comment]
@DanyCaissy looks good. The PRO is currently called "Visualizer: Tables and Charts Manager for WordPress AddOn" - do you want to change that too? If you do you can do it in visualizer-pro.php

**Pull request merged**
