### PR TITLE
Fix update axis baseline color

### LINKED ISSUE #925: Line chart color options not working as expected. [in visualizer block options only]
### Description:
When you try to change the Horizontal axis base line color using color settings, it is not respecting the color choice and shows zero effect and when you change the color of the vertical axis base line, it changes the color of the horizontal axis instead of its own axis.

I also noticed that when you use the default color options given in settings, the color is not changing but when you pick the color using a color picker the changes are made easily. [this is happening in block options only ]

### How to reproduce the Axis base line color issue :
1. Go to the visualizer menu and create a new line (or column) chart.
2. Go to a page /post and add a new block chart.
3. Use the existing chart that you created in the first step.
4. Go to Block settings > Advanced options > Horizontal axis settings > base line color.
5. Try to change the color of the base line.
6. Observe that nothing changes.
7. Now navigate to Vertical axis settings > base line color
8. Try to change the color of the base line.
9. Observe that changes are being made but in the Horizontal axis base line instead of the vertical axis.

### How to reproduce the default color option issue :
1. Go to the visualizer menu and create a new line (or column) chart.
2. Go to a page /post and add a new block chart.
3. Use the existing chart that you created in the first step.
4. Go to Block settings > Advanced options > Horizontal axis settings > Axis Text color [same for vertical axis settings].
10. Try to change the color using default color options.
11. Observe that Nothing changes.
12. Now try to change the color using the color picker option.
13. Changes are being made.

### Expected behavior:

- The color of the horizontal axis base line should be changed using the color options available in horizontal axis settings.
- The color option of the vertical axis setting should change the color of vertical axis base line instead of the horizontal axis base line.
- The axis text color should be changed using the default color options.

### Current behavior:

- The color of the horizontal axis base line is not changing at all using the horizontal axis settings.
- The color settings of the vertical axis are interfering with the horizontal axis and changing its base line color instead of its own
- The axis text color is changed only using a color picker [default color options not working ]

### Reference:
Screenshots for the first bug :
Screenshot_4
Screenshot_9

Loom video for the first bug :
https://www.loom.com/share/e0ddeb2c89884920ac9f9f31259a4915

Screenshot for the second bug : 
Screenshot_6
Screenshot_5

### Technical info
* WordPress version: 6.0.1
* Visualizer version: 3.7.10

### PR DESCRIPTION
**Pull request by girishpanchal30**
Close #925

### CODE REVIEW

**Comment by irinelenache** [comment]
@girishpanchal30 Tested and updating colors in block settings works fine, until the colors are selected from the Neve palette, can we do something about this?
You can check here:
```
https://visualizer.s1-tastewp.com/2022/08/23/test-line-chart-colors/
Username: irinel  
Password: s5pLLp6pFFw
```

**Comment by girishpanchal30** [comment]
@irinelenache I have fixed the above mentioned issue. Please check with the latest commit.

**Comment by irinelenache** [comment]
@girishpanchal30 I checked now and the mentioned issue persists for me

**Comment by girishpanchal30** [comment]
@irinelenache I think this issue persists due to the test instance file cache.
Can you please add the below PHP constant in the wp-config.php file to avoid file cache?
`define( 'VISUALIZER_TEST_JS_CUSTOMIZATION', true );`

It's working for me
Thanks

**Comment by vytisbulkevicius** [comment]
Hey @girishpanchal30,

Should we document this constant in our knowledgebase
`define( 'VISUALIZER_TEST_JS_CUSTOMIZATION', true );` ?

Could you provide a bit of context what are the scenarios this could be happening to add it to the documentation?

**Comment by girishpanchal30** [comment]
@vytisbulkevicius

When we define this constant in the wp-config.php file it enqueues js with filetime in the `ver` query string instead of the plugin version.
Basically, this constant help to avoid server/browser file cache.

I hope you understood

Thanks

**Pull request merged**
