### PR TITLE
Avoid breaking with ChartJS

### PR DESCRIPTION
**Pull request by HardeepAsrani**
Added a check to stop the Block from breaking with ChartJS until proper
support is added. Related to #373

@contactashish13

### CODE REVIEW

**Comment by contactashish13** [comment]
@SilviuDinu can you please test this?

**Comment by HardeepAsrani** [comment]
@SilviuDinu Make a DataTable, ChartJS and Google Chart and then only Google Chart should appear, while rest shouldn't appear. Make sure there are no errors. Let me know if you need help.

**Comment by SilviuDinu** [comment]
I will see to it

**Comment by SilviuDinu** [comment]
@HardeepAsrani @contactashish13 
just like Hardeep said, only the google chart was visible. The block is now working -> https://embed.vidyard.com/share/XTfNV9mFVv5SrMymy44137?

**Pull request merged**
