### PR TITLE
Improve create chart workflow from Visualizer Block

### LINKED ISSUE #1119: Create a chart link in gutenberg block is not redirecting users to create a chart, but to chart library
### Description

Create a chart link in gutenberg block is not redirecting users to create a chart, but to chart library

### Step-by-step reproduction instructions

1. Add a visualizer block
2. Click on create a new chart

### Screenshots, screen recording, code snippet or Help Scout ticket

_No response_

### Environment info

_No response_

### Is the issue you are reporting a regression

No

### PR DESCRIPTION
**Pull request by Soare-Robert-Daniel**
### Summary

Ported the Chart Library workflow to the Visualizer Block for chart creation. Same workflow as in https://github.com/Codeinwp/visualizer/pull/1136

### Will affect visual aspect of the product

NO

### Screenshots 

https://github.com/Codeinwp/visualizer/assets/17597852/b44dd3ac-1fa2-4cd9-8dcb-5f690e04e1be

### Test instructions

- Insert a new visualizer block and click to create a new chart
- You should see the Popup
- After Creating the chart, the block will update with the newly created chart

## Check before Pull Request is ready:

* [x] I have [written a test](CONTRIBUTING.md#writing-an-acceptance-test) and included it in this PR
* [x] I have [run all tests](CONTRIBUTING.md#run-tests) and they pass
* [x] The code passes when [running the PHP CodeSniffer](CONTRIBUTING.md#run-php-codesniffer)
* [x] Code meets [WordPress Coding Standards](CONTRIBUTING.md#coding-standards) for PHP, HTML, CSS and JS
* [x] [Security and Sanitization](CONTRIBUTING.md#security-and-sanitization) requirements have been followed
* [x] I have assigned a reviewer or two to review this PR (if you're not sure who to assign, we can do this step for you)

Closes #1119

### CODE REVIEW

**Comment by Soare-Robert-Daniel** [comment]
I give it another shot by having the same modified version for `wp.media` as in the dashboard/Chart Library. ( `window.visualizer.media.view.Chart` via `view.js` and `library.js`)

But I got a lot of errors and weird behaviour that I dropped the idea -- at this point, it is better to rewrite the whole thing.

**Comment by vytisbulkevicius** [comment]
@Soare-Robert-Daniel,

The experience I get with this build is different, I get a new tab opened with chart library, create the chart there, need to close that tab and then I'm back to the page where I see the chart created - https://vertis.d.pr/v/YRPd4V

It's better than before but if we can have the behavior from your screencast which is loading it in an iframe not another tab that would be ideal.

**Comment by Soare-Robert-Daniel** [comment]
Updated the code using the solution from https://github.com/Codeinwp/visualizer/pull/1136

**Review by preda-bogdan — APPROVED** [review]

**Comment by irinelenache** [comment]
@Soare-Robert-Daniel Tested and after adding the chart and clicking the **Save** button, it will keep loading and a console error is thrown https://vertis.d.pr/v/81w7Kt

Can be checked here:
```
 Admin area URL: https://internalend.s3-tastewp.com/wp-admin 
 Username: irinel 
 Password: RfISOKXpUJ0 
```

**Comment by Soare-Robert-Daniel** [comment]
@irinelenache, when you re-test this, please use another instance of tasteWP 🙏

**Comment by vytisbulkevicius** [comment]
To me it works as expected now

**Pull request merged**
