### PR TITLE
Support for AMP

### PR DESCRIPTION
**Pull request by contactashish13**
https://github.com/Codeinwp/visualizer-pro/issues/111

### CODE REVIEW

**Comment by ineagu** [comment]
will this work automatically?

**Comment by contactashish13** [comment]
Yes. It will replace the visualizer short code output with the iframe code and the iframe code will point to a virtual page that spits out the chart.

**Comment by ineagu** [comment]
@rodica-andronache you managed to get this working? it would be great to have this feature on our blogs.

**Comment by contactashish13** [comment]
@ineagu Using this PR, I've created a test page. It seems to be working well. 

https://formidable-cicada.jurassic.ninja/x/amp/ vs. https://formidable-cicada.jurassic.ninja/x/

It looks like the recommended method for using google charts is indeed the one we have used. Maybe we can think of refining it and ironing out the problems instead of a completely different approach? I'm sure it will help as a feature for users as well.

**Comment by ineagu** [comment]
I am not sure right now the approach we took is best, there are still frontend issues ( https://www.dropbox.com/s/4914g6anjeilwzp/Screenshot%202019-03-07%2010.29.56.png?dl=0 ), but more importantly we aren't really doing what we should ( provide a really fast mobile experience) and we still load the huge amount of scripts google brings over.

I guess until maybe AMP come up with a standard for that which would be ideal, we can have a "fallback" parameter on the shortcode, where users can specify an image or standard table. Optionally we can have a setting to have the fallbacks not only on AMP, but mobile. What we do I think is killing 3g

**Comment by contactashish13** [comment]
I agree. If we want to load anything google, we have to fire the scripts to even create the image so that's probably not the best behavior. I'll explore loading a table with the data. A datatable table will load it's script and case as well so maybe we should just load an HTML table?

**Comment by contactashish13** [comment]
@ineagu you can test the same URL now. I'm now showing an HTML table for AMP.

**Comment by ineagu** [comment]
It seems like a good compromise for me right now. To avoid any potential issues we can have a filter to disable this if users want along with documentation explaining how and our reasoning behind.

**Pull request merged**
