### PR TITLE
Fix issue with Table Chart

### PR DESCRIPTION
**Pull request by HardeepAsrani**
This fixes the issue which we have been having for weeks is now fixed. The table chart should work fine. To make sure it's fixed, @DanyCaissy can try to update with this on http://cute-chicken.w6.wpsandbox.pro/ to make sure it works.

Fixes https://github.com/Codeinwp/visualizer/issues/506 & https://github.com/Codeinwp/visualizer/issues/526

cc @contactashish13

### CODE REVIEW

**Comment by DanyCaissy** [comment]
@HardeepAsrani 

If I try to add the same table twice, using the front-end, it looks like this: https://i.imgur.com/JRNNvmC.png

I suspect it might be something to do with the ID being duplicated or something. 

This is on chicken after adding this PR to it. The 'load more' issue also still happens, but that was for another ticket right?

**Comment by HardeepAsrani** [comment]
Can you do it on sandbox? As I wasn't able to reproduce this on my end and multiple table charts work just fine. @DanyCaissy

**Comment by DanyCaissy** [comment]
@HardeepAsrani Yes, the previous image is on sandbox.

http://cute-chicken.w6.wpsandbox.pro/wp-admin/post.php?post=14&action=edit


[2019-09-18_11-42-36.zip](https://github.com/Codeinwp/visualizer/files/3627303/2019-09-18_11-42-36.zip)

**Comment by HardeepAsrani** [comment]
Ahaa, got it. Thanks. I'll get it fixed. :)

**Comment by HardeepAsrani** [comment]
@DanyCaissy This should fix both issues, the Table chart appearing twice & this one: https://github.com/Codeinwp/visualizer/issues/532#issuecomment-532742639

Let me know if it works.

**Comment by contactashish13** [comment]
@HardeepAsrani in the future it would be best if you could add @DanyCaissy as a reviewer for the PR so that I can merge only when he approves the PR.

**Comment by DanyCaissy** [comment]
@HardeepAsrani I've added your dev branch to cute-chicken and the same issues still occur for me.

This page: http://cute-chicken.w6.wpsandbox.pro/wp-admin/post.php?post=14&action=edit

**Comment by DanyCaissy** [comment]
Just to be sure, I did:


git clone https://github.com/HardeepAsrani/visualizer
git checkout development
npm composer zip

**Comment by HardeepAsrani** [comment]
I rebased with the latest 3.3.1 branch and I get this after setting up the plugin. Is there an issue with the plugin? @contactashish13 

Screen Shot 2019-09-25 at 4 54 57 am

**Comment by contactashish13** [comment]
@HardeepAsrani had that been a regular problem @DanyCaissy would have faced it too. I've tested the 3.3.1 branch with and without pro and I don't see this error. Please check if its not a problem at your end.

**Comment by HardeepAsrani** [comment]
I tried again and it happened again to me. It also happened with the Codeinwp repo. :(

**Comment by contactashish13** [comment]
@HardeepAsrani can you share a fresh barebones public instance where I can troubleshoot this?

**Comment by HardeepAsrani** [comment]
@DanyCaissy Were you able to reproduce the double table issue again? It's working just fine. Might have been cache. :)

**Comment by DanyCaissy** [comment]
@HardeepAsrani  On your version now it wont show me tables at all to add: https://i.imgur.com/ZdQVqWs.png

I also don't see all of the charts

http://cute-chicken.w6.wpsandbox.pro/wp-admin/post.php?post=70&action=edit

**Comment by HardeepAsrani** [comment]
There are two issues:

- One is with block not showing ChartsJS but still counting them on the count which is an issue.

- Another is the issue with multiple table causing ID issue, which works just fine when I tried the latest Visualizer from WordPress.com: https://www.loom.com/share/c3bc0b9695c3424a8477c418e2041651

I guess you are not able to reproduce on your side because of the first issue. Every chart has different meta, depending on when they were made. You should delete all other charts but table to reproduce and see if it works.

Meanwhile, I'll solve the first issue.

**Comment by HardeepAsrani** [comment]
@DanyCaissy I've fixed the issue on that Sandbox site. Can you see if it works now?

**Comment by DanyCaissy** [comment]
Heya @HardeepAsrani 

I wasn't able to reproduce the issue where some tables were invisible, so maybe that was fixed successfully.

There still seems to be something wrong with the pagination or count, right now it looks like this: 

https://i.imgur.com/l2n5qh2.png

However, if I click load more, nothing happens (there is not 7th chart to display, the 7th is chartjs).

The desired behaviour would be that if there is 6 charts, there should be no 'load more' button.

**Comment by HardeepAsrani** [comment]
Yea, that's a known issue, unfortunately. We can't know if there any charts left to load unless we load all of them at once. We can load the total count but since we're filtering out ChartsJS charts, it makes it bit complex. :(

**Comment by HardeepAsrani** [comment]
@DanyCaissy ^

**Comment by DanyCaissy** [comment]
Well, if that's the only issue it causes, people can live with it.

**Pull request merged**
