### PR TITLE
Fix render chart issue when creating first time chart

### PR DESCRIPTION
**Pull request by girishpanchal30**
Close Codeinwp/visualizer-pro#316

### CODE REVIEW

**Comment by irinelenache** [comment]
@girishpanchal30 I managed to replicate the issue and tried to test this fix. After applying this PR and making changes to the chart, i get a notice and an error in the console https://vertis.d.pr/0SuYYu

**Comment by girishpanchal30** [comment]
@irinelenache I have tested with the local machine and it's working fine to me, It seems like you have an issue with server timeout (Execution timeout). Can you re-test with a different instance?

**Comment by irinelenache** [comment]
@girishpanchal30 
On a tastewp instance, when i try to import the data i get an error (Table has no columns) https://vertis.d.pr/Os99qc .

I tried on another jurassic instance and i still get the same error (when i'm checking the chart in incognito mode or from another browser), you can check here:
```
https://outstanding-platypus.jurassic.ninja/2021/11/02/test-visualizer-2/
user: demo
password: fDVZdb3K0Xts
```

**Comment by girishpanchal30** [comment]
@irinelenache The chart render issue has been fixed when user not logged-in. Can you re-verify it?

**Comment by irinelenache** [comment]
@girishpanchal30 Tested again and now the issue seems to be fixed 👍 

@vytisbulkevicius If you have time, can you please have a second look to be sure about this? After that, this can be moved to **Ready**

**Comment by vytisbulkevicius** [comment]
@irinelenache @girishpanchal30,

Hm, I've downloaded this build - https://verti-artifacts.s3.amazonaws.com/visualizer-bugfix-316-797e9b7d/visualizer.zip

And Tried to create a chart using a CSV file provided in the original issue as the source for the Line chart - https://docs.google.com/spreadsheets/d/e/2PACX-1vSMr0_Y3PQMWTmIlWRKO35B9HQq6wUUpitGQb0ewIKG49s1IeZ2hnQgctWPXT-AvkOS0_Ogr2InggyM/pub?gid=1581975214&single=true&output=csv

The chart loads in the Visualizer Library - https://vertis.d.pr/sMie0A
But nothing in the front-end - https://vertis.d.pr/8fYjsG (tried both Gutenberg block and shortcode ways and also added a simple line chart with the default data above to show that default chart is loading)

Also, an interesting thing is that if I open the chart again I don't see the source that I added before, might be related or not but the source should be saved in the chart. Recording - https://vertis.d.pr/UB4xlE

Can be checked here - https://common-caiman.jurassic.ninja/2021/11/11/9/
https://common-caiman.jurassic.ninja/wp-admin
User: demo
Password: EfGRY1ZxYsxb

P.S I'm using only the free version here.

**Comment by irinelenache** [comment]
@vytisbulkevicius Thanks for checking 🙏 
Indeed, the chart doesn't load in frontend neither when only Visualizer lite is used or when both Lite and Pro are installed.
I verified again with the Live csv import and sometimes it's working as expected, sometimes i have to add again the csv link and import in order to work as expected.
Also, as Vytis said, the source link should be saved in import settings

cc @girishpanchal30

**Comment by girishpanchal30** [comment]
@vytisbulkevicius & @irinelenache
I have reviewed the visualizer free plugin code and it seems like the PRO version is required to save some setting fields.

Please check the code here...
Free - https://github.com/Codeinwp/visualizer/blob/bugfix/316/classes/Visualizer/Module/Chart.php#L1103
Pro - https://github.com/Codeinwp/visualizer-pro/blob/master/inc/addon.php#L137

Do you want to move the Pro plugin code into a free plugin? In this case, we need to move `visualizer_pro_chart_schedule` filter code.

**Comment by vytisbulkevicius** [comment]
hey @girishpanchal30,

So this is needed just for saving the CSV file as the source? With the free version it's not needed to have the periodical update as it's a feature of PRO version and with the Free version you should only be able to import it once, the problem is that the source file is not saved as it was before.

Another problem is that chart doesn't render on the front-end with that source added (maybe related to the fact that source is not saved, I'm not sure about it).

Well, in conclusion, we don't want to move the periodical sync functionality to the free version of the plugin, we just need it to work as a one-time import as it was working this way all the time. So if this filter that you mentioned was always in the PRO version only I don't think that we need to move it to the free version.

**Comment by girishpanchal30** [comment]
@vytisbulkevicius Fixed the chart render issue on the frontend side, @irinelenache can you re-test?

**Comment by irinelenache** [comment]
@girishpanchal30 Tested again and now seems like everything is working fine 👍 Will move this to **Ready**

**Pull request merged**
