### PR TITLE
database import

### PR DESCRIPTION
**Pull request by contactashish13**

### CODE REVIEW

**Comment by abaicus** [comment]
@contactashish13 it seems that when you remove all conditions you can't add back others. Can you take a look at this? e.g. below in this situation 

image

**Comment by contactashish13** [comment]
@abaicus thanks! Have fixed it.

**Comment by abaicus** [comment]
@contactashish13 Thank you 👍

**Comment by abaicus** [comment]
@contactashish13 Also, when you remove the conditions, the containers still remain empty in the markup. 
image

**Comment by contactashish13** [comment]
@abaicus doesn't seem to be happening for me:

image

**Pull request merged**
