### PR TITLE
Add support of interval role in chart

### PR DESCRIPTION
**Pull request by girishkrishaweb**
Close Codeinwp/visualizer-pro#258

### CODE REVIEW

**Comment by girishkrishaweb** [comment]
@irinelenache We have added interval roles support with an extra configuration option. See the screenshot

image_2021_06_09T06_47_40_345Z
image_2021_06_09T06_48_08_876Z

e.g: { "intervals": { "lineWidth":2, "barWidth": 0.5, "style": "line" } }

**Comment by irinelenache** [comment]
@girishkrishaweb Can you please provide some more test instructions? I see that interval needs 2 values to be defined, i don't know where should they be added. Thank you!

**Comment by girishkrishaweb** [comment]
@irinelenache Yes, Sure! We follow the google intervals document to develop it. Here is the link https://developers.google.com/chart/interactive/docs/gallery/intervals

We have defined 2 values to set intervals.

1. As you have seen above, in The first image we have added **Special Role** Interval.
2. We have added an additional configuration where you can apply additional changes to the interval role settings in the chart.

The first configuration is enough for the preview of interval functionality but if you have additional changes then you can apply through the second additional settings.

**Comment by irinelenache** [comment]
@girishkrishaweb Thanks, i managed to use and test the feature. It works as expected 👍

**Pull request merged**
