### PR TITLE
Fix multiple charts loading issue

### LINKED ISSUE #883: Multiple charts on the same page load inconsistently
### Description:
This doesn't look related to the lazy-loading feature as I turned it off and this still happens.
Client reported that charts on his website load not every time, I'm able to replicate it, sometimes all the chart loads and sometimes just one of them or none of them. 
Charts do not load on the Firefox browser all the time.

His website is here - https://keywordsentiment.com/
I also exported the charts and tried to replicate them on the test instance here - https://petiterequest.tastewp.com/2022/01/20/483/

Recording of the issue: https://vertis.d.pr/dzF7LA (I'm switching between the private browsing mode and regular mode, in private browsing mode where I'm not logged in as admin it happens almost all the time).
Interesting thing is that opening developer tools sometimes fix the issue so probably screen resizing triggers the chart loading.

### How to reproduce:
1. Open this page - https://keywordsentiment.com/ or this one - https://petiterequest.tastewp.com/2022/01/20/483/ 
2. Try reloading page multiple times, try incognito mode and Firefox browser
3. You should face the issue that charts are sometimes not loaded, sometimes there is an error in the console about google not defined, or jQuery not defined, sometimes there is no errors.

### Expected behaviour:
Charts should be loaded.

### Current behaviour:
Charts are not loaded sometimes.

### Reference:
Issue can be checked here for several days:
 Admin area URL: https://petiterequest.tastewp.com/wp-admin
 Username: bvytis 
 Password: OxWguiFb7go
 
 https://secure.helpscout.net/conversation/1750303307/305322

### Technical info
* WordPress version: 5.8.3
* Plugin version: 3.7.3

### PR DESCRIPTION
**Pull request by girishpanchal30**
Close #883

### CODE REVIEW

**Comment by irinelenache** [comment]
@girishpanchal30 Tested and when i first open the page in incognito, not all charts are loading (they load when i resize the window). After refreshing the page, it works as expected. https://vertis.d.pr/gUKd9y

You can check the issue here:
```
 Admin area URL: https://ringrhythm.tastewp.com/2022/01/21/test-charts-fix/
 Username: irinel 
 Password: Dqhr9jevUKs 
```

**Comment by girishpanchal30** [comment]
@irinelenache You need to disable lazy load chart here ( https://tinyurl.com/yawfvw95 )
or using this filter `add_filter( 'visualizer_lazy_load_chart', '__return_false' );`

Thanks

**Comment by irinelenache** [comment]
@girishpanchal30 So if lazy rendering is enabled, charts aren't supposed to properly load when i first open the page in incognito mode?

**Comment by girishpanchal30** [comment]
@irinelenache I'll check the first-time lazy load chart rendering issue and update you here...

**Comment by girishpanchal30** [comment]
@irinelenache Please retest again, the above issue is fixed
Thanks

**Comment by irinelenache** [comment]
@girishpanchal30 Tested again and now everything works fine, thanks 👍

**Pull request merged**
