### PR TITLE
Add Skip button for second step of Chart Creation

### PR DESCRIPTION
**Pull request by Soare-Robert-Daniel**
### Summary

Add the possibility to close the second step and the Chart Creation workflow

### Will affect visual aspect of the product

YES

### Screenshots 

image

### Test instructions

- Add a New chart and select its type
- You should see the Skip button and when pressed it should close the popup/iframe

## Check before Pull Request is ready:

* [x] I have [written a test](CONTRIBUTING.md#writing-an-acceptance-test) and included it in this PR
* [x] I have [run all tests](CONTRIBUTING.md#run-tests) and they pass
* [x] The code passes when [running the PHP CodeSniffer](CONTRIBUTING.md#run-php-codesniffer)
* [x] Code meets [WordPress Coding Standards](CONTRIBUTING.md#coding-standards) for PHP, HTML, CSS and JS
* [x] [Security and Sanitization](CONTRIBUTING.md#security-and-sanitization) requirements have been followed
* [x] I have assigned a reviewer or two to review this PR (if you're not sure who to assign, we can do this step for you)

Closes https://github.com/Codeinwp/visualizer-pro/issues/457

### CODE REVIEW

**Review by GrigoreMihai — APPROVED** [review]

**Comment by vytisbulkevicius** [comment]
@Soare-Robert-Daniel,

I don't think "Skip" button makes sense here, the purpose of the feature request is to Cancel the creation of the chart if you don't want it to be created (changed your mind). I see the behavior that is now added with this PR is that both "Skip" and "Create chart" buttons do the same - they create a chart.

That's why I mentioned it should be "Cancel" button so you just close the popup and chart doesn't get created (same behavior as clicking outside the popup that is not intuitive).

**Comment by Soare-Robert-Daniel** [comment]
@vytisbulkevicius 

I think we need to rename also the Crate Chart to Finish

In the chart creation flow, after you press Next, the chart is already created.

That is why I put Skip button instead of Cancel. 

Should we still put Cancel and a delete chart mechanism to delete the created chart or just rename Create Chart to something else and keep a minimal change?

**Comment by vytisbulkevicius** [comment]
@Soare-Robert-Daniel,

Chart doesn't get created on Next, if I click outside the popup as stated above the popup is closed and chart is not in the library, screencast: https://vertis.d.pr/v/dPMUuS

So we don't need any mechanism, only to have "Cancel" button that closes the popup.

**Comment by Soare-Robert-Daniel** [comment]
@vytisbulkevicius, what I said is true, but I completely forgot that the skipped charts are not shown in the library by default.

When you select a chart, the database creates an entry with the status `auto-draft`. When you press `Create Chart`, the status changes to `publish`.

Screenshot 2024-05-07 at 11 00 19

Technically, the first step should have `Cancel` and `Create Chart`, and the second step should have `Skip` and `Finish` to better reflect the real workflow. 

Looking closely at some parts of the code, it seems when you create a new chart, at the same, it deletes all the previous charts in `auto-draft,` which conflicts with the idea of `Skip` and `Finish` since the draft will always be deleted.

> [!NOTE]
> This was an overview of how things work. I will make a quick change to switch the label to `Cancel`.

**Pull request merged**
